"""Build data/faers_demo.db: a SYNTHETIC demo FAERS-style dataset.

*** THIS IS DEMO DATA, NOT REAL FDA DATA ***
Rows are generated locally so the text-to-SQL tool works offline and the
schema matches the real FAERS fields we load in weekend 3. Counts loosely
follow the public patterns (GLP-1 drugs: GI-heavy reports; metformin:
lactic acidosis signal) so demos feel realistic - but no row is a real
adverse-event report.

Rebuild any time:  python -m tools.seed_faers_demo
"""

from __future__ import annotations

import config  # noqa: F401  (loads .env)

import random
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "faers_demo.db"

# reaction pool per drug: (reaction, relative weight)
DRUG_REACTIONS = {
    "semaglutide": [
        ("NAUSEA", 30), ("VOMITING", 18), ("DIARRHOEA", 15), ("DECREASED APPETITE", 8),
        ("CONSTIPATION", 7), ("ABDOMINAL PAIN", 6), ("PANCREATITIS", 3),
        ("GASTROPARESIS", 3), ("DIZZINESS", 5), ("FATIGUE", 5),
    ],
    "tirzepatide": [
        ("NAUSEA", 28), ("DIARRHOEA", 17), ("VOMITING", 16), ("DECREASED APPETITE", 10),
        ("CONSTIPATION", 7), ("ABDOMINAL PAIN", 6), ("PANCREATITIS", 3),
        ("INJECTION SITE REACTION", 5), ("FATIGUE", 5), ("ERUCTATION", 3),
    ],
    "retatrutide": [
        ("NAUSEA", 26), ("VOMITING", 15), ("DIARRHOEA", 15), ("DECREASED APPETITE", 9),
        ("CONSTIPATION", 8), ("HEART RATE INCREASED", 6), ("PANCREATITIS", 4),
        ("ABDOMINAL PAIN", 6), ("FATIGUE", 6), ("DIZZINESS", 5),
    ],
    "metformin": [
        ("NAUSEA", 16), ("DIARRHOEA", 15), ("BLOOD GLUCOSE INCREASED", 14),
        ("DRUG INEFFECTIVE", 12), ("FATIGUE", 11), ("LACTIC ACIDOSIS", 10),
        ("VOMITING", 10), ("ACUTE KIDNEY INJURY", 9), ("WEIGHT DECREASED", 8),
        ("DYSPNOEA", 8),
    ],
    "empagliflozin": [
        ("URINARY TRACT INFECTION", 20), ("GENITAL MYCOLOGICAL INFECTION", 15),
        ("EUGLYCAEMIC DIABETIC KETOACIDOSIS", 8), ("POLYURIA", 12), ("THIRST", 10),
        ("HYPOGLYCAEMIA", 8), ("DEHYDRATION", 10), ("NAUSEA", 8),
        ("BACK PAIN", 5), ("FATIGUE", 4),
    ],
    "liraglutide": [
        ("NAUSEA", 27), ("VOMITING", 16), ("DIARRHOEA", 14), ("DECREASED APPETITE", 9),
        ("PANCREATITIS", 4), ("CHOLELITHIASIS", 5), ("CONSTIPATION", 7),
        ("HEADACHE", 7), ("FATIGUE", 6), ("DIZZINESS", 5),
    ],
}

OUTCOMES = [("Other", 55), ("Hospitalization", 25), ("Life-Threatening", 7),
            ("Death", 3), ("Disability", 5), ("Required Intervention", 5)]
COUNTRIES = [("US", 60), ("DE", 10), ("GB", 8), ("FR", 6), ("CA", 6),
             ("IN", 5), ("AU", 5)]
SEXES = [("F", 55), ("M", 43), ("UNK", 2)]
ROWS_PER_DRUG = 75  # 6 drugs -> 450 demo rows


def _weighted(rng: random.Random, pairs: list[tuple[str, int]]) -> str:
    return rng.choices([p for p, _ in pairs], weights=[w for _, w in pairs], k=1)[0]


def build(db_path: Path = DB_PATH) -> int:
    rng = random.Random(42)  # fixed seed: identical DB on every rebuild
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()

    with sqlite3.connect(db_path) as conn:
        conn.execute(
            """CREATE TABLE faers_reports (
                   primaryid INTEGER PRIMARY KEY,
                   drug_name TEXT NOT NULL,
                   reaction TEXT NOT NULL,
                   sex TEXT,
                   age INTEGER,
                   country TEXT,
                   outcome TEXT,
                   report_date TEXT
               )"""
        )
        conn.execute(
            "CREATE TABLE _demo_notice (note TEXT)"
        )
        conn.execute(
            "INSERT INTO _demo_notice VALUES (?)",
            ("SYNTHETIC DEMO DATA generated by tools/seed_faers_demo.py - "
             "not real FDA FAERS reports. Schema and patterns only.",),
        )

        primaryid = 10000000
        rows = 0
        for drug, reactions in DRUG_REACTIONS.items():
            for _ in range(ROWS_PER_DRUG):
                primaryid += rng.randint(1, 40)
                month = rng.randint(1, 12)
                day = rng.randint(1, 28)
                year = rng.choice([2023, 2024, 2024, 2025, 2025])
                conn.execute(
                    "INSERT INTO faers_reports VALUES (?,?,?,?,?,?,?,?)",
                    (
                        primaryid,
                        drug,
                        _weighted(rng, reactions),
                        _weighted(rng, SEXES),
                        rng.randint(18, 85),
                        _weighted(rng, COUNTRIES),
                        _weighted(rng, OUTCOMES),
                        f"{year}-{month:02d}-{day:02d}",
                    ),
                )
                rows += 1
    return rows


if __name__ == "__main__":
    n = build()
    print(f"Demo FAERS database written to {DB_PATH} ({n} synthetic rows).")
    print("Reminder: this is DEMO data, not real FDA reports.")
